### ISSUE TITLE
Define Kubernetes YAMLs in the corresponding service subdirectory

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#14] opened 2018-08-01 10:24 UTC
Each service should ideally provide it's own kubernetes configuration for `deployment.yaml` and `service.yaml` in a subdirectory. 

Affected services:
* communication-router
* flows-operator
* integration-content-repository
* scheduler
* crud monitoring

We should also have a consistent naming and folder structure for the infrastructure, e.g.:
* Kubernetes definitions should always be in a folder named _k8s_ whithin the project folder
* Use a consistent naming pattern: _deployment.yaml_ and _service.yaml_ for the definitions
* Ingress configuration should be place in a different repository (e.g. OIH-Infrastructure)
* every Microservice need to have a checkable endpoint to have a liveliness and readiness check for the K8s

**Comment by philecs** [comment] 2018-11-05 15:35
@sachmerz duplicate of #72 as definition of YAMLs is part of the guidelines?

**Closed as completed** 2019-02-04 17:14 UTC
Labels: general
