### ISSUE TITLE
Common Namespaces: "oih-dev-ns"

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#269] opened 2019-01-31 15:20 UTC
As a quality manager, responsible for testing, I want to use the pipeline so that services will be deployed automatically, therefore, all namespaces need to be the same one.

---

**Acceptance Criteria:**
- [ ] All namespaces will be "oih-dev-ns"

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment] 2019-02-04 07:52
Duplicate of #254

**Closed by philecs** 2019-02-04 07:52 UTC
Labels: Elastic.io
